Repository vanorsigma/neuro-chat-elo, pull requests merged in 2024-08, with the labels that each got.

#6 Refactor out chat messages to an enum
  rust/chatdownloader/src/chatlogprocessor.rs
  rust/elo/src/_types/clptypes.rs
  rust/elo/src/lib.rs
  rust/elo/src/metadata/badges.rs
  rust/elo/src/metadata/basic_info.rs
  rust/elo/src/metadata/metadatatrait.rs
  rust/elo/src/metadata/mod.rs
  rust/elo/src/metadata/special_role.rs
  rust/elo/src/metrics/bits.rs
  rust/elo/src/metrics/copypastaleader.rs
  rust/elo/src/metrics/emote.rs
  rust/elo/src/metrics/metrictrait.rs
  rust/elo/src/metrics/mod.rs
  rust/elo/src/metrics/subs.rs
  rust/elo/src/metrics/text.rs
Labels: enhancement

#8 Frontend fixes
  web/src/app.html
  web/src/lib/carousel.svelte
  web/src/lib/leaderboard.svelte
  web/src/lib/podium.svelte
  web/src/lib/revealCard.svelte
  web/src/lib/revealCards.svelte
  web/src/routes/+layout.svelte
  web/src/routes/+page.svelte
  web/src/routes/rankingCard.svelte
Labels: enhancement

#9 Leaderboard SVG updates
  web/src/lib/leaderboard.svelte
  web/src/lib/rankitem.svelte
  web/src/lib/rankitems/bronze.svelte
  web/src/lib/rankitems/gold.svelte
  web/src/lib/rankitems/normal.svelte
  web/src/lib/rankitems/silver.svelte
  web/src/routes/+page.svelte
  web/src/routes/rankingCard.svelte
Labels: enhancement

#11 Fix percentile function
  rust/elo/src/leaderboards/leaderboardtrait.rs
Labels: bug

#12 Update docs
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  LICENSE
  README.md
  screenshots/screenshot-01.png
Labels: documentation

#19 Move PR template to the correct directory
  .github/pull_request_template.md
Labels: documentation

#15 Protobuf Leaderboard Storage
  .github/workflows/backfill-rust.yml
  .github/workflows/trigger.yaml
  .gitignore
  models/leaderboardExportTypes.proto
  rust/chatdownloader/src/chatlogprocessor.rs
  rust/elo/Cargo.toml
  rust/elo/build.rs
  rust/elo/src/_types/clptypes.rs
  rust/elo/src/_types/leaderboardtypes.rs
  rust/elo/src/leaderboards/leaderboardtrait.rs
  rust/elo/src/metadata/badges.rs
  stage.sh
  web/README.md
  web/package-lock.json
  web/package.json
  web/src/lib/menu.svelte
  web/src/lib/ranks.ts
Labels: enhancement

#20 Moving Emote Processing into SevenTVClient
  rust/chatdownloader/src/backfill.rs
  rust/chatdownloader/src/chatlogprocessor.rs
  rust/chatdownloader/src/main.rs
  rust/elo/src/lib.rs
  rust/elo/src/metrics/bits.rs
  rust/elo/src/metrics/copypastaleader.rs
  rust/elo/src/metrics/emote.rs
  rust/elo/src/metrics/metrictrait.rs
  rust/elo/src/metrics/mod.rs
  rust/elo/src/metrics/subs.rs
  rust/elo/src/metrics/text.rs
  rust/twitch_utils/Cargo.toml
  rust/twitch_utils/src/lib.rs
  rust/twitch_utils/src/seventvclient.rs
  rust/twitch_utils/src/seventvtypes.rs
  rust/twitch_utils/src/twitchtypes.rs
Labels: enhancement

#22 Create directory for gen if it doesn't exist
  web/package.json
Labels: enhancement

#24 Correcting 7TV response types
  rust/twitch_utils/src/seventvclient.rs
  rust/twitch_utils/src/seventvtypes.rs
Labels: bug

#23 Reveal improvements + Frontend fixes
  web/src/lib/loadableFlexContainer.svelte
  web/src/lib/podium.svelte
  web/src/lib/rankingCard.svelte
  web/src/lib/revealCard.svelte
  web/src/lib/revealCardBasic.svelte
  web/src/lib/revealCardCollection.svelte
  web/src/lib/revealCards.svelte
  web/src/routes/+layout.svelte
  web/src/routes/+page.svelte
  web/src/routes/page.css
  web/static/audio/drum.mp3
  web/static/audio/yippie.mp3
Labels: bug, enhancement

#26 Update pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#14 Partner Leaderboards
  rust/elo/src/leaderboards/mod.rs
  rust/elo/src/leaderboards/partnersonly.rs
  web/src/lib/menu.svelte
  web/src/lib/ranks.ts
  web/src/lib/revealCards.svelte
  web/src/routes/+page.svelte
Labels: enhancement

#25 Remove the constructor from MetadataTrait
  rust/elo/src/metadata/badges.rs
  rust/elo/src/metadata/basic_info.rs
  rust/elo/src/metadata/chat_origin.rs
  rust/elo/src/metadata/metadatatrait.rs
  rust/elo/src/metadata/mod.rs
  rust/elo/src/metadata/special_role.rs
Labels: enhancement

#29 Backfill gets last 5 VOD ids
  rust/chatdownloader/src/backfill.rs
  rust/chatdownloader/src/main.rs
  rust/twitch_utils/src/lib.rs
Labels: enhancement
